### ISSUE TITLE
@angular/cli flags

### ISSUE THREAD

**Issue by osnoser1** [dolanmiu/ng-cli-angular#3]
Hi, excelent work with this extension.

It would be ideal to be able to receive `@ angular/cli` parameters through ` nge` such as `-prod`,` --build-optimizer`, etc.

Beforehand thank you very much.

**Comment by dolanmiu** [comment]
Yes, flags are planned for future releases!

**Comment by dolanmiu** [comment]
Done!

https://github.com/dolanmiu/ng-cli-electron/releases/tag/1.2.1
